test reports

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -35,4 +35,19 @@ jobs:
       - name: Test
         working-directory: ${{ github.workspace }}
         # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-        run: ctest --test-dir _build_\${{ matrix.preset_build_architecture }} --build-config ${{ matrix.preset_build_configuration }}
+        run: ctest --test-dir _build_/${{ matrix.preset_build_architecture }} --build-config ${{ matrix.preset_build_configuration }} --output-junit TEST-${{ matrix.preset_build_architecture }}-${{ matrix.preset_build_configuration }}.xml
+
+      - name: JUnit Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: _build_/**/TEST-*.xml
+
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.7.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          name: My Tests
+          path: _build_/**/TEST-*.xml
+          reporter: jest-junit
+          fail-on-error: true
